function[V] = norm3(a,b,c)
    V = sqrt( ...
        norm(a)^2*norm(b)^2*norm(c)^2 ...
        + 2*dot(b,c)*dot(c,a)*dot(a,b) ...
        - norm(a)^2*dot(b,c)^2 ...
        - norm(b)^2*dot(c,a)^2 ...
        - norm(c)^2*dot(a,b)^2 ...
        );
end